### ISSUE TITLE
Umožnit zadat opisovače

### ISSUE THREAD

**Issue by horacekj** [fi-ksi/web-backend#100]
Bude umožněno zadat řešitele, kteří opisují, ke konkrétní úloze. Na základě toho se pak bude správně počítat to, jeslti je řešitel úspěšný řešitel.

**Comment by horacekj** [comment]
@BorysekOndrej Navrhuji ke každému `correction` přidat binární flag `cheat`, který bude možný nastavit zatrhnutím checkboxu při opravování. Souhlas?

**Comment by BorysekOndrej** [comment]
Na první pohled ok, souhlasím. Jen nevím, jak se řeší nemožnost stát se úspěšným řešitelem. Každý, kdo jednou podvádí, se v tom ročníku nemůže stát úspěšným řešitelem?

**Comment by horacekj** [comment]
Přesně tak. Radši prosím i na druhý polhed, ať to tak nemusíme předelávat...

**Comment by BorysekOndrej** [comment]
Chceme si ukládat informaci, kdo podváděl s kým? Osobně si myslím, že netřeba ve strojově čitelném formátu, stačí to myslím psát do opravení.

**Comment by horacekj** [comment]
Přesně tak, souhlasím.

**Comment by BorysekOndrej** [comment]
Ok, tak v tom případě nevidím žádný problém. Jsem pro tvoje řešení.

**Comment by horacekj** [comment]
Pribyly tyto věci:

* každý uživatel má boolovský atribut `cheat`.
* každý profil má boolovský atribut `cheat`.
* každé `evaluation` má nastavitelný atribut `cheat`. Pozor: `evaluation` je až to úplne nejvnitřnější: jedná se o konkrétní opravu pro konkrétního uživatele, modul a ID opravy (jeden uživatel může jeden modul nechat vyhodnotit vícekrát). Tedy podvod není vlastnost celé úlohy, ale modulu.

Doporučuji podvod zobrazovat v opravování u modulu, minmálně u velkých úloh je typicky jen jeden modul. U dalších typů modulů možná ani není nutné checkbox zobrazovat. Zobrazil bych ho jen když na to bude někde vhodné místo, aby se oprava zbytečně nezvyšovala na monitoru.

Funkční na kyzikosu.
