### ISSUE TITLE
action add_achievement selže při přidání stejného achievementu z dvou úloh

### ISSUE THREAD

**Issue by BorysekOndrej** [fi-ksi/web-backend#112]
action add_achievement selže při pokusu přidat stejný achievement stejnému řešiteli z jiné úlohy.
V rámci jedné úlohy lze přidávat opakovaně.
Selhání se ukazuje jako "Server odpověděl chybovým kódem, kontaktuj organizátora.", jelikož backend vrátí HTTP 500.

**Comment by horacekj** [comment]
Chceme tohle podporovat? Jakože aby bylo možné udělit stejnou trofej z více úloh?

**Comment by BorysekOndrej** [comment]
Za mě není třeba sledovat fakt, že by řešitel měl mít trofej z více úloh. Z mého pohledu úplně stačí, aby se tím nezabilo vyhodnocení jinak správného řešení.
Tzn. v případě, že řešitel trofej již má, backend ji neudělí znovu, ale řešení uzná.

**Comment by horacekj** [comment]
Ok, implementuji.
