### ISSUE TITLE
Tlačítko Exportovat řešitele exportuje pouze > 0 bodové

### ISSUE THREAD

**Issue by BorysekOndrej** [fi-ksi/web-backend#115]
Tlačítko Exportovat řešitele exportuje pouze > 0 bodové, dle mého názoru by mělo exportovat všechny kteří něco udělali v rámci ročníku. Vidíš to Honzo jinak?

**Comment by horacekj** [comment]
Ne výsledkovce jsou také jen ti > 0 bodů. Chceme teda všechny? Mně je to celkem jedno.

**Comment by BorysekOndrej** [comment]
V tlačítku export bych čekal všechny, nutně tam ale asi být nemusí. Jen si musíme dát pozor, až budeme znovu tahat statistiky.

**Comment by horacekj** [comment]
V exportu jsou všichni (i nulabodoví) a již dlouho tam byli. Prosím o kontrolu.
