### ISSUE TITLE
Po odoslaní e-mailu chlapcom sa odošle aj dievčatám

### ISSUE THREAD

**Issue by danieltimko** [fi-ksi/web-backend#117]
Odoslal som e-mail všetkým úspešným riešiteľom, vybral som pohlavie "Chlapci". Počet odoslaných e-mailov sa ale zhodoval s počtom všetkých úspešných riešiteľov - vrátane dievčat.

**Comment by BorysekOndrej** [comment]
Dneska jsou to zkusil otestovat na Kyzikosu, vypadá to, že to funguje správně. Jdu tedy poslat email o tom, že je vydaný nový ročník, všem loňským řešitelům, a uvidíme, zda se nějaký problém ukáže tam.

**Comment by BorysekOndrej** [comment]
I odeslání hlavního mailu vypadá ok. Zavírám tenhle issue jako Cannot reproduce.
