### ISSUE TITLE
Upgrade na Python 3.8

### ISSUE THREAD

**Issue by BorysekOndrej** [fi-ksi/web-backend#118]
V rámci diskuzí o 1. vlně nového ročníku vyvstala otázka verze Pythonu. Python 3.8 má mimo jiné dobré nové výpisové helpery, velmi nápomocné k debugování. Bylo by fajn to zvážit, můžeme to ale udělat v průběhu ročníku. Upgrade z Pythonu 3.5 na 3.8 by měl být mostly painless a převážně server-side záležitost.

Následující věci je třeba zvážit:
- je vhodné, abychom řešitelům nabízeli instalaci stejné verze, jako máme server side. Občas se nějaké chování liší, např zda jsou slovníky řazené či ne (vlastnost Pythonu 3.6+).
- Když upgradujeme server side, neměli bychom ideálně nechat řešitele na starší verzi. Ale je to ta lepší varianta, než aby řešitelé měli novější verzi, než je na serveru.

**Comment by BorysekOndrej** [comment]
Více orgů vyjádřilo touhu po novějším Pythonu, například kvůli f-stringům. Bylo by rozumně možné jít na novější verzi ještě před začátkem ročníku?

**Comment by horacekj** [comment]
Tohle je obecně docela pain. Python na serveru je přímo ten python, který je aktuálně v Debian stable. Bohužel 3.8 není ani v backports. Já se na to pořádně podívám a pokusím se nějak hezky nasadit.

**Comment by BorysekOndrej** [comment]
Honza nasadil Python 3.7.3, což je taky velký improvement. Díky!

**Comment by esoadamo** [comment]
Debian 11 má Python 3.9.2, takže teď už jsme dokonce issue překonali :slightly_smiling_face:
