### ISSUE TITLE
Úloha mající pouze bonusový modul rozbije celý web

### ISSUE THREAD

**Issue by BorysekOndrej** [fi-ksi/web-backend#122]
Úloha mající pouze bonusový modul rozbije celý web. 

> Anička na to dnes narazila. Měl jsem chvilku na to mrknout, frontend se rozbije, protože backend vrací na některé endpointy 500, nejspíš je to tedy (primárně) problém backendu. Zda si s tím pack poradí frontend je otázka, uvidíme až bude opravený backend.

Hlášení od Matěje z loňska:

> Pokud má úloha jediný modul a označis ho jako bonusový, tak když to deploynes, tak spadne strom uloh (jen pro ty, co by měli vidět tu úlohu ve stromu —tzn orgove) i orgovsky seznam uloh, kde se deployuje

> 0 Backend responded with error

> Já jsem nemohl ani načíst ten orgovský seznam úloh. tedy ani cokoliv deploynout. A ron to deploynul jen proto, že to měl přednačtené.

Causes fi-ksi/web-frontend#382

**Comment by horacekj** [comment]
Vyřešeno.

**Comment by BorysekOndrej** [comment]
Když se do úlohy, která má pouze bonusový odevzdávací modul, odevzdá soubor, tak se po reloadu už nenačte endpoint tasks, a to ani pro konkrétní úlohu, tak ani pro seznam úloh.

Reproducer je například pomocí https://kyzikos.fi.muni.cz/ulohy/146
- Nahraj do úlohy nějaký soubor a odevzdej.
- Reload (nebo nějaká jiná akce, která znovu zavolá endpoint).

0 THE BACKEND RESPONDED WITH AN ERROR
