### ISSUE TITLE
Testy spouští nejen tlačítko odevzdat, ale i spustit.

### ISSUE THREAD

**Issue by BorysekOndrej** [fi-ksi/web-backend#123]
Created by https://github.com/fi-ksi/seminar/issues/242

@ ondra
> Historie toho je, že si opakovaně stěžovali orgové, že když řešitelé dají spustit, tak se přiloží a spustí testy. To znamená, že řešitelé pak dostávají náhodné timeouty, exception z kódu, který není jejich, a mnoho dalšího. A jelikož mi to nahlašovali jako problém frontendu, tak jsem to zareportoval za ně. (A zjevně do špatného repo)

Dle Honzy to původně byla featura.

**Comment by horacekj** [comment]
Při "Spuštění" se nespustí `eval.py`. Nic víc s tím nelze dělat, protože `check` je uvnitř sandboxu a tam je asi zbytečné rozlišovat, jestli je to spuštění nebo opravení. Aktuální (nový) framework nikdy nevyhodí výjimku do spuštění, která se ve skutečnosti stala až na testech.
