### ISSUE TITLE
V informačním mailu o opravení se někdy posílá špatný počet bodů

### ISSUE THREAD

**Issue by BorysekOndrej** [fi-ksi/web-backend#130]
Letos byla úloha REDUKOVANÉ HLAVOLAMY, která byla nestandardní. Je to defacto velká úloha, která ale má pouze programovací modul, takže ji systém považuje za malou.
https://ksi.fi.muni.cz/ulohy/363

Daliborovi několik řešitelů napsalo, že v mailu obdrželi informaci o tom, že mají > 10 bodů (například 30, nebo 24).

V modulu opravování se ukazují správné hodnoty, stejně tak výsledkovka vypadá docela ok.

Problém se manifestoval například pro řešitele Lukáš Pavelka.

**Comment by horacekj** [comment]
Nepočítalo se s tím, že úloha, u které se bude posílat notifikační email, může mít u jednoho modulu více odevzdání. Opraveno.
