### ISSUE TITLE
Oddělit vyhodnocení a spuštění programovacího modulu

### ISSUE THREAD

**Issue by horacekj** [fi-ksi/web-backend#132]
Jak? Návrh:

* `check.py` (aktuální)
* přidat: `exec.py`

Merge skriptu se předá argument říkající, o co se jedná (`check`, `exec`) a ten řekne, jaký soubor (`check.py`, `exec.py`) se má spustit v sandboxu.

**Comment by BorysekOndrej** [comment]
To zní super. 👍

**Comment by horacekj** [comment]
Hotovo.
