### ISSUE TITLE
\r\n v jedné z větví v semináři může zablokovat deploy pro všechny úlohy

### ISSUE THREAD

**Issue by BorysekOndrej** [fi-ksi/web-backend#148]
Aničce se nějak povedlo (možná tím, že použila VS Code přímo na GitHubu) nechtěně [dát do repositáře](https://github.com/fi-ksi/seminar/commit/97a0feb96aa652acd045dbb872c7a8e6be5ab4af) konce řádků, které nejsou povolené v rámci [.gitattributes](https://github.com/fi-ksi/seminar/blob/master/.gitattributes). Deploy proběhl v pořádku, ale následně to Git na serveru normalizoval. Tím se soubory stali modified, a blokovali deploy všech úloh. Manuálně opraveno tím, že jsem udělal [commit](https://github.com/fi-ksi/seminar/commit/97a0feb96aa652acd045dbb872c7a8e6be5ab4af) opravující konce řádků a deploynul jsem ho. Následně už všechny další úlohy šli deploynout.

Je otázka, zda to nějak řešit systematicky. Ideálně by se do repositáře neměli takové soubory dostat, .gitattributes by to měl řešit automaticky. Nevíme, co se pokazilo, akutní problém to ale není. Nynější instance vyřešena, je to jen do budoucna.

Closes [seminar#596](https://github.com/fi-ksi/seminar/issues/596)

**Comment by esoadamo** [comment]
https://github.com/fi-ksi/seminar/pull/760/commits/754fe6f4c13ea8fec230cc8b358664543c3ac039 upravuje job po každém commitu tak, že sama opraví a commitne případné chybně formátované soubory
