### ISSUE TITLE
Odesílání emailů: Nefunguje filtrování dle pohlaví

### ISSUE THREAD

**Issue by BorysekOndrej** [fi-ksi/web-backend#160]
Při odesílání mailů o K-SCUKu jsme narazili na to, že mail pro kluky i holky se poslal 48 řešitelům, nejspíš tedy nefunguje filtrování dle pohlaví.

PS: Dneska jsem do odesílání mailů sahal, protože nefungovalo ani filtrování podle úspěšného řešitelství. Byl to ale pouze [jednořádkový commit](https://github.com/fi-ksi/web-backend/commit/4aaef3ec515939f9fd8f8b64ae9faaf2ef924c2f), který by to způsobit neměl.

**Comment by esoadamo** [comment]
https://github.com/fi-ksi/web-backend/blob/4aaef3ec515939f9fd8f8b64ae9faaf2ef924c2f/endpoint/admin/email.py#L69

Vypadá to, že se filtruje buď podle úspěšného řešitelství nebo podle pohlaví.
