### ISSUE TITLE
Vlastní tagy se neparsují správně

### ISSUE THREAD

**Issue by esoadamo** [fi-ksi/web-backend#161]
Viz https://github.com/fi-ksi/web-frontend-angular/issues/40

**Comment by ItsMACO** [comment]
Parsovacie funkcie máme momentálne iba pre `<ksi-collapsible>` a `<ksi-pseudocode>`. Tie sa volajú pred konvertovaním tasku cez pandoc. Tie parsery sú príliš komplexné, toto by bolo super naplánovať na Hackathon so spoločným effortom s frontendom.

**Comment by esoadamo** [comment]
Já se teď na to dívám a vypadá to, že pokud pandoc dostane `div`, tak to funguje správně. Staré parsery zatím asi modifikovat nebudu, zkusím ale pro `ksi-tip` (a případné další) vytvořit funkci, která to převede na `<div class="ksi-custom ksi-tip">`. Vůči tomu by měla být poté úprava FE minimální a mohlo by to fungovat

**Comment by ItsMACO** [comment]
Ak by to pomohlo, ja som si včera napísal takúto expression `(?<=<ksi-tip[^>]*>)(?:\n)*|(?:\n)+(?=<\/ksi-tip>)`, ktorá by mala byť schopná vybrať prázdne riadky hneď za opening tagom a hneď pred closing tagom `ksi-tip`-u. Problém však je, že `re` nepodporuje look-behind ( `?<=` v `(?<=<ksi-tip[^>]*>)` ), ktorý má variabilnú dĺžku ( `[^>]*` v `(?<=<ksi-tip[^>]*>)` ). Ak by sa ti to pozdávalo, možno to vieš prepísať.

**Comment by esoadamo** [comment]
Super, díky! Já teď testuju na kyzikosu fix, vypadá to, že hloupé nahrazení za `div`-y na BE a pak na FE zase zpět funguje krásně a nic se nerozbíjí :slightly_smiling_face: 

![Snímek z 2022-07-12 13-02-19](https://user-images.githubusercontent.com/15877754/178475737-6a3e1776-7b1c-4793-aaad-85272e9e203b.png)

**Comment by esoadamo** [comment]
https://github.com/fi-ksi/web-backend/commit/517328eaa3a5347b3534b7d50e6d979e4e66add6
Funguje pro samotné ksi-tip, pro ksi-tip vnořené do collapsible bloku se ještě dějí nepravosti někde jinde.

**Comment by BorysekOndrej** [comment]
Parsování asi není opravené správně, nyní nefunguje `author`, pokud celý blok není uzavřený do `
```{=html}`.
Ukázkou je následující commit v rámci úlohy, kterou jsem odkazoval výše.

https://github.com/fi-naskoc/seminar/pull/32/commits/a86725e15afdb9650ed8cb690e3b74e4deb7e619

**Comment by esoadamo** [comment]
To je zvláštní, z nějakého důvodu ten atribut něco (asi Pandoc?) přejmenuje. Udělám fix na FE.
```html
<div class="ksi-custom ksi-tip" title="Mějte kreditovou rezervu" data-author="4">
<p>V každém semestru (a obzvláště v tom prvním) si doporučuji zapsat dostatek předmětů, abyste zvládli postoupit do dalšího semestru (&gt;= 20 kreditů) i v případě, že jeden z předmětů nedáte.</p>
</div>
```

**Comment by esoadamo** [comment]
@BorysekOndrej mělo by to být OK ve verzi "220712.164758" -- prosím, zkus odstranit `\`\`\`{=html}` a pokud to bude fungovat, zavři tuto issue

https://github.com/fi-ksi/web-frontend-angular/commit/c41015474e7f120b1cff1ce6091af09dff51c47f

**Comment by BorysekOndrej** [comment]
Vypadá, že funguje. Díky!
