### ISSUE TITLE
Přejít do diskuze odkazuje na nevalidní odkaz (mailing)

### ISSUE THREAD

**Issue by danyroza** [fi-ksi/web-backend#175]
Např. 
![image](https://user-images.githubusercontent.com/25553099/185983000-d537ecde-500e-45e0-a0bd-2c6fe1e0ffd4.png)
zde odkazuje tlačítko "Přejít do diskuse" na https://naskoc.fi.muni.cz/ulohy/1/diskuse což je nevalidní.

Správně by mělo být možná https://naskoc.fi.muni.cz/ulohy/1#diskuze ? (pouze tip)

**Comment by esoadamo** [comment]
Vyvíjí se v https://github.com/fi-ksi/web-backend/tree/discussion-email-routes

**Comment by esoadamo** [comment]
Vyřešeno
