### ISSUE TITLE
Nefungují odkazy na konci emailu o upozornění na nový příspěvek v diskuzi

### ISSUE THREAD

**Issue by danyroza** [fi-ksi/web-backend#180]
Odkazy na konci mailu vedoucí k diskuzi, opravení a spuštění nefungují.

Tento problém ztěžuje práci autorům i garantům, kteří nejsou schopní snadno dohledat spuštění a kód řešitele tak, aby u něj mohli hledat chybu.

![image](https://user-images.githubusercontent.com/25553099/192142539-d5d284b8-b6f6-4e53-860f-e16e540a5a4c.png)

**Comment by esoadamo** [comment]
Na tohle se poslední dobou, pokud vím, nic neměnilo. Mohl bys prosím ukázat zdrojový kód takového emailu?

**Comment by danyroza** [comment]
Konkrétně poslední mail, co mi přišel

```
Ahoj,\
k tvé úloze [Úvod do OOP](https://ksi.fi.muni.cz/ulohy/506) na
[https://ksi.fi.muni.cz](https://ksi.fi.muni.cz/) byl přidán nový
komentář:

*Jakub Bučka:*

Dobrý deň,

Keď sa snažím svoj kód otestovať, tak dostávam správu **Metoda
check\_integrity nefunguje dle očekávání.** Skúšal som si napísať
vlastné testy aj pre špeciálne prípady a kód mi beží bez problémov.
Pozeral som si aj ako kód beží v Python Tutor, ale stále neviem zistiť
kde je chyba. Je teda niečo na čo by som si mal dávať väčsí pozor alebo
mi niečo uniká ?

[Přejít do diskuze.](https://ksi.fi.muni.cz/ulohy/506/diskuse) [Přejít
na
opravení.](https://ksi.fi.muni.cz/admin/opravovani?participant_=3604&task_=506)
[Přejít na
spuštění.](https://ksi.fi.muni.cz/admin/execs?user=3604&module=889)

Hezký den přeje\
![KSI Web](https://ksi.fi.muni.cz/img/karlik_color.png){width="40"}
```

**Comment by esoadamo** [comment]
Jasné, už chápu. To je tím, že ještě není implementováno nové admin rozhraní. Asi bychom mohli zahardocodovat dočasně adresu do starého admina
