### ISSUE TITLE
Nechodí maily organizátorům na gmail

### ISSUE THREAD

**Issue by esoadamo** [fi-ksi/web-backend#181]
Poslední dobou nechodí uživatelům registrovaným s gmail adresou emaily a vrátí se s následujícím chybovým hlášením:
```
    gmail-smtp-in.l.google.com[108.177.127.27] said: 550-5.7.1 [147.251.49.7]
    Our system has detected that this message is not RFC 550-5.7.1 5322
    compliant: duplicate headers. To reduce the amount of spam sent 550-5.7.1
    to Gmail, this message has been blocked. Please review 550 5.7.1  RFC 5322
    specifications for more information.
    ca12-20020a170906a3cc00b00783757c8e5esi6262769ejb.931 - gsmtp (in reply to
    end of DATA command)
```
Nevím, jestli je to bug na BE nebo na mail serveru FI, jelikož se mi stejné hlášení *jednou* vrátilo, když jsem posílal mail ze svého MUNI mailu přes Thunderbird na celé KSI

**Comment by BorysekOndrej** [comment]
Afaik ten problém je téměř výhradně s následující situací:

Mail poslaný z KSI rozhraní má v kopii ksi@fi 
-> Přijde na IS emaily, kde mají organizátoři nastavené přesměrování na Gmail
-> Gmail je odmítne.

Hádám tedy, že je spíš nějaký problém v přeposílání nebo naší mailové skupině.

**Comment by esoadamo** [comment]
Máš pravdu, teď jsem to prošel a jsou to orgové. Nevím tedy, kde jsem přišel na to, že jsou to i řešitelé

**Comment by esoadamo** [comment]
Vypadá to, že se nám posílají dvě `To` hlavičky, z nichž jedna se prázdná. To bude snad ta chyba.

```
: Action: failed
: Status: 5.7.1
: Remote-MTA: dns; gmail-smtp-in.l.google.com
: Diagnostic-Code: smtp; 550-5.7.1 [147.251.48.3] This message is not RFC 5322
:     compliant, the issue is: 550-5.7.1 duplicate To headers. To reduce the
:     amount of spam sent to Gmail, 550-5.7.1 this message has been blocked.
:     Please review 550 5.7.1  RFC 5322 specifications for more information.
:     qf4-20020a1709077f0400b008eb27de1fa6si12347886ejc.8 - gsmtp

: Date: Mon,  6 Mar 2023 11:57:17 +0100 (CET)
: To: 
: To: <řešitelé mail>
: Cc: <ksi mail>
: From: <ksi mail>
: Subject: [KSI] Bonusová úloha a Discord
```
