### ISSUE TITLE
Stránka s úlohou sa nenačíta

### ISSUE THREAD

**Issue by michalstanik1** [fi-ksi/web-backend#187]
Pravidelne, v deň nahlasovania zakaždým, sa mi stáva, že keď otvorím akúkoľvek URL s úlohou (pristúpim priamo k úlohe pomocou jej URL), napr. https://ksi.fi.muni.cz/ulohy/536, tak sa tam iba točí Karlík a text úlohy sa nenačíta. Keď dám refresh, tak sa už všetko načíta v poriadku.

**Comment by michalstanik1** [comment]
Podľa Adama to _vypadá na nějaký špatný souběh mezi přihlášením a načtením stránky_.

**Comment by danyroza** [comment]
Mně se to podařilo replikovat tak, že jsem měl 2 okna, v jednom úlohu a v druhém jsem se odhlásil. Pak přístup na úlohu vede k nekonečnému načítání Karlíka.

Na frotnendu je to error 403 a možná je problém spíš tam 🤔

**Comment by danyroza** [comment]
Tohle dělá i ve chvíli, kdy nejsem přihlášený vůbec a pokusím se vstoupit na stránku úlohy přímo.

**Comment by esoadamo** [comment]
Mělo by být opraveno na FE
