### ISSUE TITLE
Hostovat databázi KSI na databázovém serveru FI, nikoliv lokálně

### ISSUE THREAD

**Issue by yaqwsx** [fi-ksi/web-backend#44]
Včera jsem se bavil s Tomášem Stanizslem. Doporučuje nám místo lokální databáze ve virtuálce používat databázový server FI - jednak získáme lepší výkon a také máme od FI garanci stability databáze.

**Comment by horacekj** [comment]
Přesunul jsem dev databázi na db.fi.muni.cz. Uvidíme, jak rozumně to bude fungovat.
* Je možné na db.fi.muni.cz zřídit více uživatelských účtů pro jednu databázi? Já bych chtěl jeden pro administraci a jeden pro přístup z webu (s omezenějšími právy).
* Má databáze "web_ksi" nějaké limity? Nebo je ještě něco, o čem bych měl vědět?
* Mohu dostat přístup ke správě databáze (skrze fadmin)? Rád bych změnil heslo.
Díky.

**Comment by vlstill** [comment]
@horacekj  podle mě máš lepší dotazovat přímo unix@fi, jsou vcelku ochotní a dostaneš od nich zaručené informace. Počítám, že přes fadmin se může dostat správce/vlastník databáze, možná by stálo za to zjisti jestli to nejde navázat místo toho na skupinu (a zřídit něco jako spolek-spravci-webu), ale je možné, že to nejde, nic tomu totiž v administraci skupiny nenaznačuje.

**Comment by repli2dev** [comment]
@horacekj přesně jak říká @vlstill, je to otázka na unix@fi. Nikdy jsem neměl víc než příhlašovací údaje k DB... (Heslo lze většinou měnit skrze DB ;-)

**Comment by horacekj** [comment]
Produkční databáze migrována na db.fi.muni.cz, phpmyadmin běží pouze na kyzikosu, snad se to odsvědčí.
