### ISSUE TITLE
Vyřešit --hard push na github

### ISSUE THREAD

**Issue by horacekj** [fi-ksi/web-backend#67]
... reset --hard origin/branch na backendu?

**Comment by yaqwsx** [comment]
Když uděláš --hard push na větvi úlohy, tak se backend rozbije? :D

**Comment by horacekj** [comment]
Ano, nedelej to.

Jan Horáček
PGP: 88E9630B 4B12 CCFF 3F26 F6A9 A0D3 C51A 42F0 6004 88E9 630B

**Comment by horacekj** [comment]
Už se nerozbije.
