### ISSUE TITLE
Moduly opravované pomocí eval.py by mohly umět vracet textové chyby

### ISSUE THREAD

**Issue by JanPokorny** [fi-ksi/web-backend#80]
Pokud je textový modul opravován pomocí skriptu, v současné době umožňuje ze skriptu vrátit pouze binární informaci "správně/špatně" pomocí návratového kódu. Bylo by super, kdyby nějakým způsobem umožňoval zobrazit textovou informaci řešiteli, například mu sdělit, kde v jeho řešení je chyba atp.

**Comment by horacekj** [comment]
Implementováno v backendu. Nově umožnuje vracet i částečné body, čeká se na frontend.
