### ISSUE TITLE
Zobrazovat celou statistiku u úloh

### ISSUE THREAD

**Issue by horacekj** [fi-ksi/web-backend#87]

**Comment by horacekj** [comment]
...může být dost velká, je to ještě na diskuzi.

**Comment by esoadamo** [comment]
https://github.com/fi-ksi/web-frontend-angular/issues/36
Na Hackatonu se navrhlo top 100 (nyní 5)

**Comment by esoadamo** [comment]
Resolved by https://github.com/fi-ksi/web-backend/commit/3df056e7c07c3c0aa0c5b3a2911f7300c3590d42
