### ISSUE TITLE
HTTP 500: Profil a Nastavení uživatele (Kyzikos)

### ISSUE THREAD

**Issue by BorysekOndrej** [fi-ksi/web-backend#93]
Na Kyzikosu mi backend vrací HTTP 500 Internal Server Error při dotazech na Profil a Nastavení uživatele.
Hlavní web funguje aktuálně správně.

**Comment by horacekj** [comment]
Zapomněl jsem zkopírovat jednu tabulku, když jsem ti kopíroval účet na developer server. Už by to mělo být opraveno.

**Comment by BorysekOndrej** [comment]
Potvrzuji funkčnost, díky!
