### ISSUE TITLE
Přidat checkbox "Nechci dostávat PS v mailech"

### ISSUE THREAD

**Issue by Krejdom** [fi-ksi/web-backend#94]
Nastavení -> E-mailové notifikace
+ "Nechci dostávat PS v mailech"

Způsobí to, že se mi do veškerých mailů (převážně upozornění na příspěvek v diskuzi) nebudou přidávat funny obrázky. Můj život bude o tolik jednodušší! O:)

**Comment by horacekj** [comment]
Implementačně náročné, PS odstraněny úplně.
