### ISSUE TITLE
Přidat možnost skrytého příspěvku v diskusi (který vidí jen autor a orgové)

### ISSUE THREAD

**Issue by JanPokorny** [fi-ksi/web-backend#95]
Nice to have, aby se řešitelé mohli ptát v diskusi i na věci přímo s jejich řešením a nemuseli psát email. Stejně tak my bychom nemuseli mazat příspěvky od řešitelů, kteří v diskusi zveřejnili svoje řešení, stačilo by je skrýt.

**Comment by horacekj** [comment]
Mně osobně přijde, že když polovina diskuze bude veřejná a druhá ne, budou v tom mít minimálně orgové zmatek. Myslíš, že je tohle je vážně věc, kterou řešitelé i orgové ocení?

Jako řešitel se můžeš vždy odkázat na odevzdané řešení, my jako orgové ho vidíme. V současné době je to podle mě docela využívané a funguje to. Navíc má org vedle odevzdaného zdrojáku hned výstupy testů, takže dokáže snadno identifikovat problém.

**Comment by JanPokorny** [comment]
Mě přijde, že v současné době je většina příspěvků v diskuzi nějaký konkrétní dotaz k řešitelovu odevzdání, a ne nějaký obecný dotaz na upřesnění zadání. Z dotazů typu "proč mi to nefunguje" a odpovědí na ně se stejně ostatní řešitelé moc nedozví.

Prošel jsem si diskuze k úlohám ve 3. vlně a ze všech příspěvků jsem našel tak 2, co by mohly zajímat ostatní (nějaké nepřesnosti v zadání).

Když o tom přemýšlím, možná bych byl rovnou pro zrušení veřejné diskuze u úloh, protože je to celkem limitující formát co se týče "konkrétních" dotazů. Pokud by řešitel pak našel nějakou nejasnost v zadání, která by mohla zajímat více lidí, dává spíše smysl aktualizovat zadání o upřesnění.

**Comment by BorysekOndrej** [comment]
Návrh umožnit skrývání věcí v diskuzi rozhodně podporuji. Většina diskuze, aspoň v mých úlohách, skutečně bývají problémy konkrétních řešitelů, a když je to něco obecného, stejně musím updatovat zadání.

Zrušení veřejné diskuze mi zase ale přijde razantní, osobně pro ni místo ještě vidím. Pro orgy myslím, že by stačilo barevně odlišit veřejné a skryté příspěvky.

PS: Odkazování na odevzdané řešení je občas dost chaos, obzvláště když řešitel napíše do diskuze a než člověk stihne odpovědět, tak řešitel odevzdá nějakou jinou verzi. Číslování řádků tak často strácí smysl.

**Comment by horacekj** [comment]
Mně to pořád přijde zbytečné. Jsem ochoten tuto feature implementovat až mě většina orgů na schůzi řekne, že to chtějí.

**Comment by horacekj** [comment]
(pak klidně issue znovu otevřu)
