### ISSUE TITLE
Některé HTML a Unicode znaky zastavují překlad md->HTML

### ISSUE THREAD

**Issue by BorysekOndrej** [fi-ksi/web-backend#97]
V úloze o kódování jsme s @GiraffeReversed narazili na to, že některé HTML a Unicode znaky rozbíjí překlad do HTML. Ony znaky a ani nic za nimi se nepřeloží (nebo neuloží do databáze).

Lokálně mi to pomocí pandocu funguje v pohodě, příkládám případně konkrétní použitý příkaz.
`pandoc -f markdown+smart -t html5+smart assignment.md -o vystup.html`

Znaky, které nefungují:
🐧 (Unicode U+1F427)
&#128039; (HTML char `&#128039;`)
&#x1F427; (HTML char `&#x1F427;`)

**Comment by horacekj** [comment]
Mně překlad prošel, jen se znak nepřeložil správně.

**Comment by horacekj** [comment]
Důvod: mysql neumí uložit více než 3-bytové unicode znaky. Je to škaredé a nechápu, proč to tak je. Změna by vyžadovala změnu `collation` tabulky, momentálně se pokouším najít jiné řešení.

**Comment by horacekj** [comment]
Došel jsem k závěru, že problém není snadno řešitelný, pobavím se s vámi osobně o tom, jak velká je to priorita.

**Comment by horacekj** [comment]
Opraveno, už by mělo fungovat.
