### ISSUE TITLE
Delší platnost refresh tokenu?

### ISSUE THREAD

**Issue by horacekj** [fi-ksi/web-backend#98]
Umožnit delší platnost refresh tokenu (umožní "permanentní" login)? Třeba 7 dní? Měsíc? Momentálně nastaveno na 24 hodin.

**Comment by esoadamo** [comment]
Resolved by https://github.com/fi-ksi/web-backend/commit/1e74d5c72de6b32b2e3a331f1ebd4d883a6a622a
Now is set to two weeks
